# Available configuration variables for the library and their default values.
# To change a value, override the variable in the application makefile, not here.

# Model of the temperature sensor. Supported models: tmp36
LIBTEMP_SENSOR ?= tmp36
