include $(MAKER_ROOT)/Makefile.pre
include $(MAKER_ROOT)/Makefile.msp

ifeq ($(LIBTEMP_SENSOR),tmp36)
LIBTEMP_REF = 1.2 # V for <= 70 degC
LIBTEMP_SLOPE_INVERSE = 100 # 1/10mV/C to volts = 1/(10/1000)
LIBTEMP_INTERCEPT = 0.5 # V (750mV at 25C)
else
$(error Unsupported temperature sensor: see LIBTEMP_SENSOR var)
endif

override CFLAGS += \
	-DLIBTEMP_REF_BITS=$(call ref,$(LIBTEMP_REF)) \
	-DLIBTEMP_SLOPE_INVERSE=$(LIBTEMP_SLOPE_INVERSE) \
	-DLIBTEMP_INTERCEPT=$(LIBTEMP_INTERCEPT) \
